cet/urls.py
from . import views
from django.conf.urls import include, url
from django.views.static import serve 
from django.conf import settings
from django.contrib.auth import views as auth_views
from .views import PasswordsChangeView
from django.urls import include, path
app_name = 'cet'

urlpatterns = [
    url(r'^$', views.index),

    url(r'^test/$', views.Reviewview.as_view() , name='test'),

    path('get_segments_branches/', views.get_segments_branches, name='get_segments_branches'),
    path('segments_update/', views.segments_update, name='segments_update'),
    path('segments_delete/', views.segments_delete, name='segments_delete'),
    path('segments_br_add/', views.segments_br_add, name='segments_br_add'),
    
    url(r'^redirectDev/$', views.redirectDev, name='redirectDev'),
    url(r'^pdf/$', views.pdf, name='pdf'), 
    url(r'^ibnr/$', views.view_ibnr, name='view_ibnr'),
    url(r'^ibnr_save/$', views.ibnr_save, name='ibnr_save'),
    url(r'^ibnr_reinitialiser/$', views.ibnr_reinitialiser, name='ibnr_reinitialiser'),
    url(r'^apercu_ibnr/$', views.apercu_ibnr, name='apercu_ibnr'),
    url(r'^resume_ibnr/$', views.resume_ibnr, name='resume_ibnr'),
    url(r'^valider_ibnr/$', views.valider_ibnr, name='valider_ibnr'),
    url(r'^view_matrice_dev/$', views.view_matrice_dev, name='view_matrice_dev'),
    url(r'^excel_matrice_ibnr/$', views.excel_matrice_ibnr, name='excel_matrice_ibnr'),
    url(r'^excel_bloc_matrice_ibnr/$', views.excel_bloc_matrice_ibnr, name='excel_bloc_matrice_ibnr'),
    url(r'^excel/$', views.excelview2, name='excel'),
    url(r'^excel_test/$', views.excelview, name='excel_test'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^pdftakaful/$', views.pdftakaful, name='pdftakaful'),
    url(r'^authentification/$', views.authentification, name='authentification'),
    url(r'^login/$', views.login_redirect, name='redirect'),
    url(r'^logout_view/$', views.logout_view, name='logout_view'),
    url(r'^genererpdf/$', views.genererpdf, name='genererpdf'),
    url(r'^genererpdftakaful/$', views.genererpdftakaful, name='genererpdftakaful'),
    url(r'^sauvegarderpdf/$', views.sauvegarderpdf, name='sauvegarderpdf'),
    url(r'^etatsexcel/$', views.etatsexcel, name='etatsexcel'),
    url(r'^kpi/$', views.kpi_view, name='kpi'),
    url(r'^kri/$', views.kri_view, name='kri'),
    url(r'^etatsexcelerm/$', views.etatsexcelerm, name='etatsexcelerm'),

    url(r'^etatsexcelgen/$', views.etatsexcelgen, name='etatsexcelgen'),

    url(r'^etatsexcelcna/$', views.etatsexcelcna, name='etatsexcelcna'),
    url(r'^tableaux_cna/$', views.tableaux_cna, name='tableaux_cna'),

    url(r'^top_list/$', views.top_list, name='top_list'),
    url(r'^management/$', views.management, name='management'),
    url(r'^super_management/$', views.super_management, name='super_management'),
    url(r'^cet_suivant/$', views.cet_suivant, name='cet_suivant'),
    url(r'^bloquer_rms/$', views.bloquer_rms, name='bloquer_rms'),
    url(r'^debloquer_rms/$', views.debloquer_rms, name='debloquer_rms'),
    url(r'^bloquer_user/$', views.bloquer_user, name='bloquer_user'),
    url(r'^debloquer_user/$', views.debloquer_user, name='debloquer_user'),
    url(r'^egal_equi/$', views.view_egal_equi, name='view_egal_equi'),
    url(r'^save_taux_egal_equi/$', views.save_taux_egal_equi, name='save_taux_egal_equi'),
    url(r'^apercu_prov_egal_equi/$', views.apercu_prov_egal_equi, name='apercu_prov_egal_equi'),
    url(r'^valider_prov_egal_equi/$', views.valider_prov_egal_equi, name='valider_prov_egal_equi'),

    
    url(r'^view_changement_mdp/$', PasswordsChangeView.as_view(template_name='main/templates/securite.html') , name='view_changement_mdp'),
    url(r'^password_change_done/$', views.success_change_password , name='success_change_password'),
]

"""views.test"""

comptes_project/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [

    url(r'^cet/', include('cet.urls', namespace='cet')),
    url(r'^admin/', admin.site.urls)
]

cet/templates/main/templates/egal_equi.html
{% extends 'main/templates/index.html' %}
{% load static %}
{% block header %}

<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    Provisons d'égalisation et d'équilibrage.
    <small> </small>
  </h1>

</section>

{% endblock %}

{% block meta %}


<style>
    label {
    text-align: right;
    clear: both;
    float:left;
    margin-right:15px;
}
/* Chrome, Safari, Edge, Opera */
input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
  -webkit-appearance: none;
  margin: 0;
}

/* Firefox */
input[type=number] {
  -moz-appearance: textfield;
}
</style>


{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
          <div class="col-sm-2">
          </div>
          <div class="col-md-7">
            <div class="box box-solid">
              <div class="box-header with-border">
              
                <h3 class="box-title">Veuillez introduire les taux :</h3>
              </div><!-- /.box-header -->
              <div class="box-body"> 
                <form action="{% url 'cet:save_taux_egal_equi' %}" method="get">
                <table>
                    <tr >
                        <td style="padding-right: 10px; padding-bottom: 10px ;"><label style="margin-top: 5px;" for="input_vie">Taux Vie</label></td>
                        <td style="padding-right: 10px; padding-bottom: 10px ;"><input type="number" id="input_vie" name="taux_vie" placeholder="Taux Vie" step=".01" required  value="{{taux_vie}}"></td>
                    </tr>
                    <tr>
                        <td style="padding-right: 10px; padding-bottom: 10px ;"><label style="margin-top: 5px;" for="input_grele">Taux Credit</label></td>
                        <td style="padding-right: 10px; padding-bottom: 10px ;"><input type="number" id="input_Credit" name="taux_credit" placeholder="Taux Credit" step=".01" required value="{{taux_credit}}"></td>
                    </tr>
                    <tr >
                        <td style="padding-right: 10px; padding-bottom: 10px ;"><label style="margin-top: 5px;" for="input_grele">Taux Grêle</label></td>
                        <td style="padding-right: 10px; padding-bottom: 10px ;"><input type="number" id="input_grele" name="taux_grele" placeholder="Taux Grêle" step=".01" required value="{{taux_grele}}"></td>
                    </tr>
                </table>
                <button class="btn btn-block btn-success btn-xs" style="width:100px"> Sauvegarder</button> 
            </form>
              </div><!-- /.box-body -->
            </div><!-- /.box -->
          </div><!-- ./col -->
                      
          <div class="col-sm-4">
          </div>
        </div>
    </div>
    <div class="container" >
        <form action="{% url 'cet:apercu_prov_egal_equi' %}" method="get">
            <button class="btn btn-block btn-success btn-xs" style="width:auto"> Aperçus CET avec Prov. egal-equi</button> 
        </form>
    </div>
        
{% endblock %}

{% block highlight_egal_equi %} class="active" {% endblock %}
{% block CET_treeview %}
  active
  {% endblock %}
  {% block CET_menu_open %}
  menu-open
  {% endblock %}
  {% block CET_menu_style %}
  style="display: block;"
  {% endblock %}

cet/templates/main/templates/genererpdf.html
{% extends 'main/templates/index.html' %}
{% load static %}
{% block header %}

<!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      COMPTE D'EXPLOITATION TECHNIQUE
      <!--<small>Control panel</small>-->
    </h1>
    <!--<ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Dashboard</li>
    </ol>-->
  </section>
  
{% endblock %}
{% block content %}

<div class="container" style="margin-top: 30px;">
  <div class="row">
    <div class="col-sm-2">
    </div>
    <div class="col-md-7">
      <div class="nav-tabs-custom"  >
        <ul class="nav nav-tabs">
          <li class="active"><a href="#tab_1" data-toggle="tab">CONVENTIONNEL</a></li>
          <li><a href="#tab_2" data-toggle="tab">RETAKAFUL</a></li>
          
          <li class="pull-right"><a href="#" class="text-muted"><i class="fa fa-gear"></i></a></li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane active" id="tab_1">
            
            <p>Bilan CONVENTIONNEL du {{ exercice }}  du {{ date_debut }} au {{today}}.</p>
            
          <div style="text-align: right; border: 0px;">
            <button  onclick="location.href = '/cet/pdf';" class="btn btn-block btn-success btn-xs"  style="width: 100px; margin-left: auto; margin-right: auto  ;margin-top: 30px;" >Générer</a> 
          </div>
          </div><!-- /.tab-pane -->
          <div class="tab-pane" id="tab_2">
            <p>Bilan RETAKAFUL du {{ exercice }}  du {{ date_debut }} au {{today}}.</p>
            
            <button  onclick="location.href = '/cet/pdftakaful';"class="btn btn-block btn-success btn-xs"  style="width: 100px; margin-left: auto; margin-right: auto ; margin-top: 30px;" >Générer</a> 
          </div><!-- /.tab-pane -->
        </div><!-- /.tab-content -->
      </div><!-- nav-tabs-custom -->
    </div><!-- ./col -->
                
    <div class="col-sm-4">
    </div>
  </div>
</div>

{% endblock %}
{% block highlight_pdf  %}
  class="active"
{% endblock %}
{% block CET_treeview %}
active
{% endblock %}
{% block CET_menu_open %}
menu-open
{% endblock %}
{% block CET_menu_style %}
style="display: block;"
{% endblock %}

cet/templates/main/templates/genererpdftakaful.html
{% extends 'main/templates/index.html' %}
{% load static %}
{% block content %}

<!-- <iframe src=" {% static '/pdf/hello.pdf#toolbar=0'%}" width="100%" height="500px">
</iframe>
  -->
  <div class="box box-danger" style ="min-width:600 ; max-width: 700px   ;height:60px" >
    <div class="box-header" style="float: left;">
      <h3 class="box-title">Bilan RETAKAFUL {{ exercice }}  du {{ date_debut }} au {{today}}.</h3>
    </div>
    <div class="box-body" style="float: right;">
          <a href="/cet/pdftakaful" class="btn btn-block btn-primary" style="width: 100px; margin-left: 30px;">Générer</a> 
    </div><!-- /.box-body -->
  </div><!-- /.box -->

{% endblock %}
{% block highlight_takaful  %}
  class="active"
{% endblock %}

cet/templates/main/templates/inDevelopment.html
{% extends 'main/templates/index.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="row">
          <div class="col-sm-2">
          </div>
          <div class="col-md-7">
            <div class="box box-solid">
              <div class="box-header with-border">
                <i class="fas fa-exclamation" style="font-size: 17px;"></i>
                <h3 class="box-title">Message</h3>
              </div><!-- /.box-header -->
              <div class="box-body">
                <p>En cours de développement </p>
                <p><b>CCR</b> Reporting.</p>
              </div><!-- /.box-body -->
            </div><!-- /.box -->
          </div><!-- ./col -->
                      
          <div class="col-sm-4">
          </div>
        </div>

{% endblock %}

cet/templates/main/templates/login.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Data Engine | Log in</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap 3.3.2 -->
    <link href=" {% static 'cet/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- Font Awesome Icons -->
    <link href="{% static 'cet/fontawesome-free-5.15.3-web/css/all.css' %} " rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="{% static 'cet/dist/css/AdminLTE.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- iCheck -->
    <link href="{% static 'cet/plugins/iCheck/square/blue.css' %}" rel="stylesheet" type="text/css" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="login-page">
    <div class="login-box" style=" text-align: center;">
      <img src="{% static 'img/login_logo.png' %}" alt="logo"  width="AUTO" height="AUTO"> 
      <div class="login-logo">
        <a href="#"><b>Data  </b> Engine</a>
      </div><!-- /.login-logo -->
      <div class="login-box-body">
        <p class="login-box-msg">Connectez-vous</p>
        <form action="{% url 'cet:authentification'  %}" method="post">
          {% csrf_token %}
          <div class="form-group has-feedback">
            <input type="text" class="form-control" placeholder="Compte" name="compte" required/>
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
          </div>
          <div class="form-group has-feedback">
            <input type="password" class="form-control" placeholder="Mot de passe" name="mdp" required/>
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
          </div>
          <div class="row">
            <div class="col-xs-8">    
              <div class="checkbox icheck">
                <!--<label>
                  <input type="checkbox"> Remember Me
                </label>-->
              </div>                        
            </div><!-- /.col -->
            <div class="col-xs-4">
              <button type="submit" class="btn btn-primary btn-block btn-flat" style="margin-bottom: 10px;">S'identifier</button>
            </div><!-- /.col -->
          </div>
        </form>

        

       <!-- <a href="#">Mot de passe oublié </a><br>-->
      {% if error == 0 %} 
        {% if messages %}
        <div class="alert alert-success alert-dismissable"  >
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <h4>	<i class="icon fa fa-check"></i> Message</h4>
            {% for message in messages %}
            <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
            {% endfor %}
        </div>
        {% endif %}
      {% endif %}
      {% if error == 1 %}
        {% if messages %}
        <div class="alert alert-danger alert-dismissable"  >
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <h4>	<i class="icon fa fa-ban"></i> Erreur</h4>
            {% for message in messages %}
            <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
            {% endfor %}
        </div>
        {% endif %}
      {% endif %}
      </div><!-- /.login-box-body -->
    </div><!-- /.login-box -->

    <footer   style="width: 100%;
    height: 28px;
    position: absolute;
    bottom: 0px; 
    left: 0px; 
    text-align: center; ">
       CCR Direction des Systèmes d'Information, Division Base de Données et Développement. Copyright 2021 ©</a>
    </footer>

    <!-- jQuery 2.1.3 -->
    <script src="{% static 'cet/plugins/jQuery/jQuery-2.1.3.min.js' %}"></script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="{% static 'cet/bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>
    <!-- iCheck -->
    <script src="{% static 'cet/plugins/iCheck/icheck.min.js' %}" type="text/javascript"></script>
    <script>
      $(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' // optional
        });
      });
    </script>
  </body>
</html>

cet/templates/main/templates/password_change_done.html
{% extends 'main/templates/index.html' %}

{% block content %}

<div class="container">
	<div style="width: 50% ; margin: 0 auto;  ">
		
		  <div class="alert alert-success alert-dismissable"  >
			  
			  <h4>	<i class="icon fa fa-check"></i> Message</h4>
			  
			  <li  > Votre mot de passe a été modifié avec succès </li>
			  
		  </div>
		
	</div>
</div>

{% endblock %}

cet/templates/main/templates/test.html
{% load static %}
<link rel="icon" href="{% static 'favicon.ico' %}">
<!DOCTYPE html>
<html>

<head>
<style>
    .error {
    color: red;
}
</style>

</head>

<body>
    <form id="myform">
        <div>
            <input type="checkbox" name="demo[]" value="colorado" />test0
            <input type="checkbox" name="demo[]" value="michigan" />test1
            <input type="checkbox" name="demo[]" value="colorado" />test2
            <input type="checkbox" name="demo[]" value="michigan" />test3
            <input type="checkbox" name="demo[]" value="colorado" />test4
            <input type="checkbox" name="demo[]" value="michigan" />test5
        </div>
        <div>
            <input type="checkbox" name="service.area" value="colorado" />colorado
            <input type="checkbox" name="service.area" value="michigan" />michigan
        </div>
        <div>
            <input type="checkbox" name="fav[]" value="skiing" />skiing
            <input type="checkbox" name="fav[]" value="volley" />volley
        </div>
        <div>
            <input type="checkbox" name="zone" value="afrique" />afrique
            <input type="checkbox" name="zone" value="europe" />europe
            <input type="checkbox" name="zone" value="asie_amerique" />asie_amerique
        </div>
        <div>
            <input type="submit" />
        </div>
    </form>
    <a href="http://docs.jquery.com/Plugins/Validation" target="_blank">Validation Documentation</a>

    <!-- jQuery 2.1.3 -->
    <script src=" {% static 'cet/plugins/jQuery/jQuery-2.1.3.min.js' %} "></script>
    <!-- jQuery validate -->
    <script src=" {% static 'cet/validate/jquery.validate.min.js' %} "></script>
    <script>
        $(document).ready(function () {

            $('#myform').validate({
                rules: {
                    'service.area': {
                        required: true
                    },
                    'fav[]': {
                        required: true
                    },
                    'demo[]': {
                        required: true
                    },
                    'zone' :{
                        required: true
                    }
                },
                errorPlacement: function (error, element) {
                    //error.insertBefore(element);
                    error.insertAfter(element.closest('div'));
                },
                submitHandler: function (form) { // for demo
                    alert('valid form');
                    return false;
                }
            });

        });

    </script>
</body>
<footer>

</footer>